# This file contains values from Cookiecutter

default_context:
  project_name: "faststream-playground"
  project_description: "Description for `faststream-playground`"
  package_name: "app"
  git_platform: "github"
  username: "a1d4r"
  git_repo_url: "https://github.com/a1d4r/faststream-playground"
  email: "a1d4r@yandex.ru"
  version: "0.1.0"
  python_version: "3.10"
  line_length: "100"
